### PR TITLE
Update CMEPS 

### PR DESCRIPTION
**Pull request by DeniseWorthen**
Issue #1 

- Removes use of ifrac_nstod in med_fraction_set

Issue #2 

- Implements correct mapping for fractional land mode when coupling_mode is set to 'nems_frac'

Additional changes:

- Creates separate DataInitialize and prep_ocn code blocks for nems modes (nems_orig, nems_frac or nems_orig_data) which are distinct from corresponding CESM modes. 
- Implements bulkflux fix for datm as in NEMS (PR # [69](https://github.com/NOAA-EMC/NEMS/pull/69))
- Adds field dictionary changes to fd_nems.yaml for CICE6.
- Removes aoflux associated field bundles from nems_orig and nems_frac modes.
- Minor cleanup of mis-spellings or other text.

 

New baselines will be required.

Related PR:
[ufs-s2s-model](https://github.com/ufs-community/ufs-s2s-model/pull/129)

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
Baselines are running on Hera and Orion.

**Comment by DeniseWorthen** [comment]
New Baselines are created on Hera and Orion. Ready for merge.

**Review by binli2337 — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
The changes to med.F90 were tested on cheyenne and did not change answers. When I ran the RT against the new (20200701) baselines I had created for this commit, the answers for some of the tests changed: cpld_fv3_ccpp_384_mom6_cice_cmeps_1d_bmark_rt
cpld_fv3_ccpp_384_mom6_cice_cmeps_2d_atm_flux
cpld_fv3_ccpp_384_mom6_cice_cmeps_ww3_1d_bmark_rt. 

I am now testing in a sandbox with and without this med.F90 change; I have not yet identified where the answers are changing. My initial tests in my sandbox are that all answers are reproducible.

**Comment by DeniseWorthen** [comment]
I believe this can be explained by an error in the RT dependency when creating a new baseline. The cold mediator re-starts were not being copied in from the newly created baseline but from the previous baseline. @MinsukJi-NOAA has identified a fix and once that is committed, I will re-create the baselines.

**Comment by DeniseWorthen** [comment]
@junwang-noaa : My compile on Orion failed with the change to the Makefile. The compile on Hera was fine. Did you test the RT on both machines?

I would like to revert this change so I can get the baselines made and the S2S updated while we figure this out.

The error on Orion was:

med.F90(746): error #6580: Name in only-list does not exist or is not accessible.   [ESMF_STATESET]
    use ESMF , only : ESMF_StateSet, ESMF_StateIntent_Import, ESMF_StateIntent_Export
----------------------^
med.F90(780): error #6632: Keyword arguments are invalid without an explicit interface.   [STATEINTENT]
         call ESMF_StateSet(is_local%wrap%NStateImp(n), stateIntent=ESMF_StateIntent_Import, rc=rc)
--------------------------------------------------------^
med.F90(780): error #6632: Keyword arguments are invalid without an explicit interface.   [RC]
         call ESMF_StateSet(is_local%wrap%NStateImp(n), stateIntent=ESMF_StateIntent_Import, rc=rc)
---------------------------------------------------------------------------------------------^
med.F90(790): error #6632: Keyword arguments are invalid without an explicit interface.   [STATEINTENT]
          call ESMF_StateSet(is_local%wrap%NStateExp(n), stateIntent=ESMF_StateIntent_Export, rc=rc)
---------------------------------------------------------^
med.F90(790): error #6632: Keyword arguments are invalid without an explicit interface.   [RC]
          call ESMF_StateSet(is_local%wrap%NStateExp(n), stateIntent=ESMF_StateIntent_Export, rc=rc)
----------------------------------------------------------------------------------------------^
compilation aborted for med.F90 (code 1)

**Comment by junwang-noaa** [comment]
It should have no impact on Orion since the ESMF version is still 800 in
s2s. I will test it on Orion with the top of s2s.

**Comment by DeniseWorthen** [comment]
New baselines have been created for both orion and hera. @junwang-noaa are we ready to merge this branch to develop?

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
