### PR TITLE
Modify CMEPS for ufsdev_ruclsm

### PR DESCRIPTION
**Pull request by RatkoVasic-NOAA**
### Specific notes

Contributors other than yourself, if any:

CMEPS Issues Fixed (include github issue #):

Are changes expected to change answers? (specify if bfb, different at roundoff, more substantial) 

Any User Interface Changes (namelist or namelist defaults changes)?

### Testing performed

Testing performed if application target is CESM:
- [ ] (recommended) CIME_DRIVER=nuopc scripts_regression_tests.py
   - machines:
   - details (e.g. failed tests):
- [ ] (recommended) CESM testlist_drv.xml
   - machines and compilers:
   - details (e.g. failed tests):
- [ ] (optional) CESM prealpha test
   - machines and compilers
   - details (e.g. failed tests):
- [ ] (other) please described in detail
   - machines and compilers
   - details (e.g. failed tests):

Testing performed if application target is UFS-coupled:
- [ ] (recommended) UFS-coupled testing
   - description:
   - details (e.g. failed tests):

Testing performed if application target is UFS-HAFS:
- [ ] (recommended) UFS-HAFS testing
   - description:
   - details (e.g. failed tests):

### Hashes used for testing:

- [ ] CESM:
  - repository to check out: https://github.com/ESCOMP/CESM.git
  - branch/hash:
- [ ] UFS-coupled, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch/hash:
- [ ] UFS-HAFS, then umbrella repostiory to check out and associated hash:
  - repository to check out:
  - branch/hash:

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@RatkoVasic-NOAA Does this fix resolve the compile error or not? I'm a bit confused.

**Comment by RatkoVasic-NOAA** [comment]
> @RatkoVasic-NOAA Does this fix resolve the compile error or not? I'm a bit confused.

No, I just followed https://github.com/ufs-community/ufs-weather-model/pull/1646#issuecomment-1483039232
Maybe I should change this to draft!?

**Comment by DeniseWorthen** [comment]
Thanks. We do need a PR if you are changing something in CMEPS. 

So we need this change, but something else is also going on because the compile is still failing, right?

**Comment by tanyasmirnova** [comment]
After 3 more commits the problem with compiling with CMEPS is resolved.

**Comment by SamuelTrahanNOAA** [comment]
This PR needs to be merged so we can merge #1646 before the deadline.

**Review by DeniseWorthen — APPROVED** [review]

**Comment by jkbk2004** [comment]
@BrianCurtis-NOAA @junwang-noaa can you approve this pr and merge?

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Pull request merged**
