### PR TITLE
Sync with ESCOMP; fix aux history files for use_float=.true.

### LINKED ISSUE #123: Update CMEPS for aux-history fix
During development of https://github.com/ufs-community/ufs-weather-model/pull/2186, it was noted that aux-history files from CMEPS were corrupted, as reported in elsewhere (https://github.com/ESCOMP/CMEPS/issues/430). 

A PR has been made to ESCOMP https://github.com/ESCOMP/CMEPS/pull/488 to resolve this issue and EMC's fork will need to be updated.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
### Description of changes

Syncs with ESCOMP, bringing back fix for aux history files so that ``use_float=.true.`` works correctly.

### Specific notes

- fixes #123

### CODE REVIEW

**Review by NickSzapiro-NOAA — APPROVED** [review]

**Comment by NickSzapiro-NOAA** [comment]
Looks good to me. My expectation is that the atm_ds2s_docn_dice test is b4b when configured to use aux history rather than mediator history. Can we include that here (+ run on more platforms) or would you prefer to keep that separate?

**Comment by DeniseWorthen** [comment]
Right now, this is no-baseline change but it probably makes sense to combine even if there is a baseline change for that one test. So I'd say go ahead and test.

**Comment by NickSzapiro-NOAA** [comment]
For atm_ds2s_docn_dice test switched to auxiliary history output  (https://github.com/NickSzapiro-NOAA/ufs-weather-model/tree/aux_cplhist)
- use_float=.false. is b4b with mediator history output
- use_float=.true. is similar but not b4b

Both ways seem to be working

**Review by dpsarmie — APPROVED** [review]
No comments

**Comment by DeniseWorthen** [comment]
@NickSzapiro-NOAA I thought you had made a comment w/rt the S4 issue that ncrcat commands/processing of ouput would not be required once you switched to aux history. I don't see any changes like that in your feature branch. Am I mis-remembering?

**Comment by NickSzapiro-NOAA** [comment]
Yes, in tests/fv3_conf/cpld_docn_dice.IN as we can write many auxiliary history times to one file directly
image

Maybe the * is misleading...I wasn't sure exactly how the files would be named. It's just 1 aux file for ice and 1 for ocean from the preceding coupled run

**Comment by DeniseWorthen** [comment]
So by setting ``ntperfile=9999`` you get all 24 1-hour timesteps in one file, correct? Is there any reason you didn't explicitly use ``ntperfile=24`` ?

**Comment by NickSzapiro-NOAA** [comment]
Yes. Since it's nice to run tests with longer forecast lengths and this is hardcoded in the ufs.configure, I left a generous cushion. If a concern, maybe the most proper is to add another atparse variable

**Comment by DeniseWorthen** [comment]
I think if you make this ``24``, then for longer forecasts you'd get more than one aux file, but each aux file would contain 24 hours. Does the stream specification not allow for more than one aux history file containing the fields required?

**Comment by NickSzapiro-NOAA** [comment]
It does. We exercise multiple stream files for cdeps in a few tests, like:
https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/tests/datm_cdeps_multiple_files_cfsr

Meanwhile, I've lost days trying to script the formatting right for flexible forecast lengths and it still not working properly.  There are some subtleties in atparse, quotes, and ESMF config format,... like with
```
!in tests/tests/hafs_regional_datm_cdeps
export DATA_ATM="\"INPUT/ERA5.TL639.2019.08.200618_subset.nc\" \"INPUT/ERA5.TL639.2019.09.200618_subset.nc\""
!in tests/parm/hafs_datm.streams.era5.IN
stream_data_files01:       @[DATA_ATM]"
```
and I ran out of time to get it working in the end. It's also unnecessary since we can just write to one file and avoid "error prone" solutions (at least for me). 

Maybe I'm just missing a main point...why split up the auxiliary history/input stream files?

**Comment by DeniseWorthen** [comment]
I don't think having the capability for "daily" aux history files is required for us to at least enable them in the test and remove the mediator history file use. But I think for general use, it would be good to not rely on one big file if possible. 

Could you make an issue on UWM (if you haven't already) to describe switching to aux history? I'm fine combining this feature branch into my UWM PR and closing that issue.

**Comment by NickSzapiro-NOAA** [comment]
Sure: https://github.com/ufs-community/ufs-weather-model/issues/2398

Yes, I'm happy to work more on it if there's interest

**Comment by DeniseWorthen** [comment]
OK, now can you make a PR to me on my fork (https://github.com/DeniseWorthen/ufs-weather-model/tree/feature/fixaux)?

**Comment by NickSzapiro-NOAA** [comment]
Please let me know if you want me to fill out the PR more fully, @DeniseWorthen

While I see use_float=.true. in ESCOMP/CMEPS, can we set use_float=.false. (more precision + b4b)?

**Comment by DeniseWorthen** [comment]
@NickSzapiro-NOAA There is currently no way to optionally configure ``use_float`` to false.

**Comment by zach1221** [comment]
@DeniseWorthen testing is complete on WM PR 2395. Please feel free to merge here.

**Pull request merged**
